### ISSUE TITLE
Is it possible to disable install?

### ISSUE THREAD

**Issue by mraible** [kesla/modify-package-dependencies#3]
I'm using this library in https://github.com/oktadeveloper/generator-jhipster-ionic, specifically in [app/index.js#162](https://github.com/oktadeveloper/generator-jhipster-ionic/blob/master/generators/app/index.js#L162). AFAICT, after adding a dependency, it runs `npm install`. Is that true, or does it simply modify `package.json` and that's it?

**Comment by mraible** [comment]
Closing because I figured out an easier way:

```javascript
const packagePath = `${this.ionicAppName}/package.json`;
const devDependencies = {
    devDependencies: {
        'generator-jhipster-ionic': packagejs.version
    }
};
this.fs.extendJSON(packagePath, devDependencies);
```

**Comment by kesla** [comment]
@mraible Hey, just for reference - no, this project is not running `npm install`
